#!/bin/bash
echo "enter the number1"
read num1

echo "enter the number number2"
read num2

if [ $num1 -gt $num2 ];then
	echo "$num1 is greater than $num2"
elif [ $num2 -gt $num1 ];then
	echo "$num2 is greater than $num1"
else
	echo "Both $num1 and $num2 are equal"
fi


